### ISSUE TITLE
Magento 2.2.x compatibility

### ISSUE THREAD

**Issue by sambolek** [trive-digital/fiskal#2]
Fiskal previously stored config mappings (e.g payment and tax mapping) as serialized string. Magento now changed the way matrixes are stored in core_config_data to JSON. 

We'll have to make adjustments to the way we're getting payment and tax mappings to use Magento serializer interface (which uses serialization on lower and json on latest Magento versions).

Reference: https://github.com/trive-digital/fiskal/blob/master/Model/Config.php#L255

**Comment by nkajic** [comment]
Do not forget https://github.com/trive-digital/fiskal/blob/master/Model/Config.php#L297
